### ISSUE TITLE
背面是怎么处理的

### ISSUE THREAD

**Issue by pekoWang** [breakstring/eInkCalendarOfToxicSoul#1]
作者你好~ 我想知道你这个背后是怎么处理的.成品厚度大改多少? 我在想能不能用微积木做一个后盖.但是支架还没想好怎么处理

**Comment by breakstring** [comment]
后盖我是用纸板剪出一个大小相同的盖上，然后用金属片和螺丝固定。
![IMG_20210102_155504_160738.jpg](https://user-images.githubusercontent.com/14105911/103453592-80c5d480-4d16-11eb-9444-36cef463eb98.jpg)
ESP32开发板用热熔胶固定在纸板上，锂电池没敢用热熔胶用的双面胶。显示面板其实很薄，不到一毫米，厚的是ESP32开发板（虽然可以剪掉针脚也还是厚）和电池。
![IMG_20210102_155536_160739.jpg](https://user-images.githubusercontent.com/14105911/103453604-9b984900-4d16-11eb-876a-825bc7377460.jpg)

**Comment by breakstring** [comment]
所以，成品的厚度主要取决于相框的厚度，以及相框安装了墨水屏后他背面能容纳电池的空间。
