### ISSUE TITLE
wifi信息在哪里设置

### ISSUE THREAD

**Issue by wispshy** [breakstring/eInkCalendarOfToxicSoul#14]

**Comment by breakstring** [comment]
WiFi信息并没有写死在代码里，而是启动后在 setup()里面875、876行左右的位置，会让设备进入ESP32的SmartConfig过程。
如果没有配置网络，那么在这个过程中会现在墨水屏上显示一个二维码，用微信扫描就可以配置网络（当然，前提是手机也连接上你想让设备连接的网络，注意需要是2.4G)，或者用乐鑫官方的ESPTouch软件来配置。
如果上次已经配置过网络，那么在这个过程中会尝试重新自动连接上，如果连接不上又进入让你配置的过程。
需要注意的是部分情况下连接不上网络会导致耗电量很大，这个流程我还在尝试优化。参见 #5 
```
  SmartConfigManager scm;
  scm.initWiFi(ShowWiFiSmartConfig);
```
具体请参见 [SmartConfigManager.h](https://github.com/breakstring/eInkCalendarOfToxicSoul/blob/main/src/SmartConfigManager.h)
