### ISSUE TITLE
更换了wifi环境，重连并没出现重新配网的二维码

### ISSUE THREAD

**Issue by Algustav** [breakstring/eInkCalendarOfToxicSoul#16]
感谢您的项目，让我快速拥有了一个可爱的桌面小台历

我发现如果将配过网的设备带到新的wifi环境，就会无限load saved credentials 并restart，没有进入重新扫码配网环节。
还有，如果配置了错误的wifi信息（比如配了个5G的wifi），也会导致无限reload。

这个设置下重试计数会不会更好一些？

再次感谢您的项目

**Comment by breakstring** [comment]
多谢反馈，我记得之前是在新网络环境下会进入重新配网环节的。前两个星期的一个版本里我做了点修改。。。可能逻辑有点问题，回头我查查。您也可以尝试回滚一个版本看看。
还有您的这个加重启计数是个很好的思路。。。反复重启其实依然会导致急剧耗电。。。重试若干次后的确不应该再反复重启了。给用户一个提示然后停止重启会更合适。
不过由于最近比较忙，我争取早点抽时间来解决吧。

**Comment by ninanxiaoguai** [comment]
按照步骤进行安装，遇到相同问题，希望可以解决，感谢感谢~

**Comment by breakstring** [comment]
抱歉，最近比较忙，等我这两天稍微抽点时间出来发现我的环境居然又出了问题。。。只能看代码盲改了。
目测应该是在我的配置网络流程中，如果之前配置过网络，然后会尝试重连，重连失败错误的进入了重启的循环。
所以 [在这个Commit中](https://github.com/breakstring/eInkCalendarOfToxicSoul/commit/23718a64c07d568d19bccde0c2c01990b933fc11) 我简单的删除了 esp_restart() 应该可以解决问题。但是。。。由于我的环境问题还没有修复，暂时无法测试。
@Algustav @ninanxiaoguai 两位可以试试看。

**Comment by breakstring** [comment]
@Algustav @ninanxiaoguai 试了下可以正常切换WiFi网络了。所以暂时关闭此issue。
