### ISSUE TITLE
做为一个小白，我是照着教程，买的一样的产品，VSCODE+PLATFORMIO编译，上传，都显示成功，就是屏幕不亮。

### ISSUE THREAD

**Issue by gzip2009** [breakstring/eInkCalendarOfToxicSoul#17]

**Comment by breakstring** [comment]
看看微雪的板子上，有1~2个拨段开关是用来设置屏幕的，看看说明书或者问问淘宝微雪的客服你的设定对不对（我的板子上只有一个开关，微博上曾经有人问我他买到的是2个开关的版本，所以我建议问微雪的客服会准确些）。同时，注意看看VSC里PlatformIO的输出里有没有啥异常信息。

**Comment by IcingTomato** [comment]
![image](https://user-images.githubusercontent.com/24474531/120069728-f2cdfa00-c0b9-11eb-9a5c-8136a32ce583.png)

5.83inch的屏幕拉到B就可以了，剩下的那个开关是负责串口转USB的电源供电
