### ISSUE TITLE
vscode build报错

### ISSUE THREAD

**Issue by corogoo** [breakstring/eInkCalendarOfToxicSoul#18]
按照教程在vscode中执行build错做之后，控制台显示如下：

/Users/xxxx/.platformio/packages/toolchain-xtensa32/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld: cannot find crt1-sim.o: No such file or directory
/Users/xxxx/.platformio/packages/toolchain-xtensa32/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld: cannot find _vectors.o: No such file or directory
collect2: error: ld returned 1 exit status
*** [.pio/build/esp32dev/firmware.elf] Error 1

**Comment by breakstring** [comment]
> 按照教程在vscode中执行build错做之后，控制台显示如下：
> 
> /Users/xxxx/.platformio/packages/toolchain-xtensa32/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld: cannot find crt1-sim.o: No such file or directory
> /Users/xxxx/.platformio/packages/toolchain-xtensa32/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld: cannot find _vectors.o: No such file or directory
> collect2: error: ld returned 1 exit status
> *** [.pio/build/esp32dev/firmware.elf] Error 1

可能还是环境问题？看您这路径是Mac下还是Linux之类的？印象中我没有出现过这样提示的错误。偶尔遇到过因为众所周知的网络问题时，我会关掉VSC把项目下的.pio目录，以及 c:\Users\username\.platformio 这个目录全都删除掉，然后重新打开VSC等它重新下载PlatformIO相关组件，然后再Build来重新自动下载各种相关的工具链和依赖库什么的。。。。您试试看？

**Comment by imindzzz** [comment]
同遇到

我是之前可以，前几天重装了系统，再编译就不行了。 。

**Comment by liujw1007** [comment]
我也遇到了同样的问题，目前来看应该是platformIO相关组件的更新导致兼容问题，不过目前还没有找到应对方法

**Comment by breakstring** [comment]
Refer to #19 (https://github.com/breakstring/eInkCalendarOfToxicSoul/issues/19#issuecomment-850274763)
