### ISSUE TITLE
4.2寸屏可用吗

### ISSUE THREAD

**Issue by deanwong** [breakstring/eInkCalendarOfToxicSoul#22]
as title

**Comment by breakstring** [comment]
> as title

需要自己适配代码，更改屏幕的驱动的参数以及对应各种图片/文字的渲染位置。

**Comment by NaturelLee** [comment]
可以看视频吗？是不是需要驱动的支持？

**Comment by breakstring** [comment]
> 可以看视频吗？是不是需要驱动的支持？

呃。。。。eInk看视频。。。这个刷新率有点困难
