### ISSUE TITLE
关于ESP32节能

### ISSUE THREAD

**Issue by lixy123** [breakstring/eInkCalendarOfToxicSoul#9]
如果用wifi, 连接路由器,获取信息的时间很难被缩短, 唤醒一次后的处理时间可能会需要10-20秒,且wifi电量消耗较大, 普通电池能撑到1-2周是其极限.如果想在节电上做到极致:
1.可考虑用两个ESP32,一个电池供电,定期蓝牙检查新信息并显示到墨水屏,快速休眠.  另一个负责缓存信息,不用电池，不考虑休眠. 前者如果5分钟一次唤醒, 每次唤醒时电量约在5秒×电流60ma, 平滩下来相当于平均1ma电流, 休眠时电流接近0,  算下来,18650电池 2000mah电量能支持约 2000×0.8/24/1= 2个月左右.   
2.不同的esp32板外围电路在休眠时耗电情况不一样,0.1-4ma不等.
3.GxEPD2有一休眠函数,如果调用,可以缩短一半秒数快速进入休眠状态,
祝你能做出更省电的墨水屏方案.

**Comment by breakstring** [comment]
> 如果用wifi, 连接路由器,获取信息的时间很难被缩短, 唤醒一次后的处理时间可能会需要10-20秒,且wifi电量消耗较大, 普通电池能撑到1-2周是其极限.如果想在节电上做到极致:
> 1.可考虑用两个ESP32,一个电池供电,定期蓝牙检查新信息并显示到墨水屏,快速休眠. 另一个负责缓存信息,不用电池，不考虑休眠. 前者如果5分钟一次唤醒, 每次唤醒时电量约在5秒×电流60ma, 平滩下来相当于平均1ma电流, 休眠时电流接近0, 算下来,18650电池 2000mah电量能支持约 2000×0.8/24/1= 2个月左右.
> 2.不同的esp32板外围电路在休眠时耗电情况不一样,0.1-4ma不等.
> 3.GxEPD2有一休眠函数,如果调用,可以缩短一半秒数快速进入休眠状态,
> 祝你能做出更省电的墨水屏方案.

非常感谢您的思路。嗯，第三点我周末抽时间研究研究。。。。多谢。

**Comment by lixy123** [comment]
> > 如果用wifi, 连接路由器,获取信息的时间很难被缩短, 唤醒一次后的处理时间可能会需要10-20秒,且wifi电量消耗较大, 普通电池能撑到1-2周是其极限.如果想在节电上做到极致:
> > 1.可考虑用两个ESP32,一个电池供电,定期蓝牙检查新信息并显示到墨水屏,快速休眠. 另一个负责缓存信息,不用电池，不考虑休眠. 前者如果5分钟一次唤醒, 每次唤醒时电量约在5秒×电流60ma, 平滩下来相当于平均1ma电流, 休眠时电流接近0, 算下来,18650电池 2000mah电量能支持约 2000×0.8/24/1= 2个月左右.
> > 2.不同的esp32板外围电路在休眠时耗电情况不一样,0.1-4ma不等.
> > 3.GxEPD2有一休眠函数,如果调用,可以缩短一半秒数快速进入休眠状态,
> > 祝你能做出更省电的墨水屏方案.
> 
> 非常感谢您的思路。嗯，第三点我周末抽时间研究研究。。。。多谢。

我其实已经做了一部分，正好看见到您的项目，周末已把项目整理完毕，并上传到了此处：
https://github.com/lixy123/ink_blueShowtxt_042
请指教！
业务时间抽空做的，完全凭个人兴趣,和商业无关.
您如果有兴趣，我把其中的esp32_blue_server部分留您做，相互交换代码，算是合做项目，您看如何？

**Comment by breakstring** [comment]
> > > 如果用wifi, 连接路由器,获取信息的时间很难被缩短, 唤醒一次后的处理时间可能会需要10-20秒,且wifi电量消耗较大, 普通电池能撑到1-2周是其极限.如果想在节电上做到极致:
> > > 1.可考虑用两个ESP32,一个电池供电,定期蓝牙检查新信息并显示到墨水屏,快速休眠. 另一个负责缓存信息,不用电池，不考虑休眠. 前者如果5分钟一次唤醒, 每次唤醒时电量约在5秒×电流60ma, 平滩下来相当于平均1ma电流, 休眠时电流接近0, 算下来,18650电池 2000mah电量能支持约 2000×0.8/24/1= 2个月左右.
> > > 2.不同的esp32板外围电路在休眠时耗电情况不一样,0.1-4ma不等.
> > > 3.GxEPD2有一休眠函数,如果调用,可以缩短一半秒数快速进入休眠状态,
> > > 祝你能做出更省电的墨水屏方案.
> > 
> > 
> > 非常感谢您的思路。嗯，第三点我周末抽时间研究研究。。。。多谢。
> 
> 我其实已经做了一部分，正好看见到您的项目，周末已把项目整理完毕，并上传到了此处：
> https://github.com/lixy123/ink_blueShowtxt_042
> 请指教！
> 业务时间抽空做的，完全凭个人兴趣,和商业无关.
> 您如果有兴趣，我把其中的esp32_blue_server部分留您做，相互交换代码，算是合做项目，您看如何？

呃。。。非常抱歉。。。我自己现在手头欠的东西都太多，完成不了，实在没有精力参与到别人的项目中了。。。

**Comment by breakstring** [comment]
> 如果用wifi, 连接路由器,获取信息的时间很难被缩短, 唤醒一次后的处理时间可能会需要10-20秒,且wifi电量消耗较大, 普通电池能撑到1-2周是其极限.如果想在节电上做到极致:
> 1.可考虑用两个ESP32,一个电池供电,定期蓝牙检查新信息并显示到墨水屏,快速休眠. 另一个负责缓存信息,不用电池，不考虑休眠. 前者如果5分钟一次唤醒, 每次唤醒时电量约在5秒×电流60ma, 平滩下来相当于平均1ma电流, 休眠时电流接近0, 算下来,18650电池 2000mah电量能支持约 2000×0.8/24/1= 2个月左右.
> 2.不同的esp32板外围电路在休眠时耗电情况不一样,0.1-4ma不等.
> 3.GxEPD2有一休眠函数,如果调用,可以缩短一半秒数快速进入休眠状态,
> 祝你能做出更省电的墨水屏方案.

刚才查了一下，您说的应该是 hibernate 函数吧？[参考这里](https://github.com/ZinggJM/GxEPD2/blob/master/src/epd/GxEPD2_583_T8.cpp)，Line 252行。
```C
void GxEPD2_583_T8::hibernate()
{
  _PowerOff();
  if (_rst >= 0)
  {
    _writeCommand(0x07); // deep sleep
    _writeData(0xA5);    // check code
    _hibernating = true;
  }
}
```
查了查[微雪墨水屏的技术手册](https://www.waveshare.net/w/upload/7/70/5.83inch_e-Paper_Datasheet.pdf)，它这是在PowerOff后面加了个让墨水屏也 Deep Sleep的动作，倒是能够更加节电。之前我只看到nextPage函数里有调用PowerOff，我以为这样就可以了，没想到还能再手工控制它也进入DeepSleep，倒是挺不错的。非常感谢！

**Comment by lixy123** [comment]
买一个好用的usb电压电流测试仪测试下,一切就都清楚了，也就20元。 如果不调用的话，墨水屏会继续耗电约5-10秒，当然最终也会休眠, 调用的话就节省了这几秒的耗电.

**Comment by breakstring** [comment]
> 买一个好用的usb电压电流测试仪测试下,一切就都清楚了，也就20元。 如果不调用的话，墨水屏会继续耗电约5-10秒，当然最终也会休眠, 调用的话就节省了这几秒的耗电.

嗯嗯，多谢提醒，测试仪已经下单了 :)

**Comment by lixy123** [comment]
没错, 是这个函数hibernate

**Comment by breakstring** [comment]
经实测，目前工作状态150mA电流，休眠后可以降低到10mA电流。
emmm.....看来那个LED灯不用想办法焊下来了 LOL
![image](https://user-images.githubusercontent.com/14105911/105352261-a3b61b00-5c28-11eb-842d-5b27ca902b06.png)
![image](https://user-images.githubusercontent.com/14105911/105352283-a9136580-5c28-11eb-929d-d727617f5208.png
[Umeter.txt](https://github.com/breakstring/eInkCalendarOfToxicSoul/files/5849306/Umeter.txt)
)
